#!/usr/bin/env bash
istanbul=./node_modules/.bin/istanbul
mocha=./node_modules/.bin/_mocha

NODE_PATH="$NODE_PATH:src" \
  NODE_ENV=test \
  $istanbul test $mocha \
  -- --require test/setup "test/**/*.js" "$@"
